default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.db[:username] %>
  password: <%= Rails.application.credentials.db[:password] %>
  host: <%= Rails.application.credentials.db[:host] %>
  port: <%= Rails.application.credentials.db[:port] %>

development:
  <<: *default
  database: rails_dev_test_development

test:
  <<: *default
  database: rails_dev_test_test